### PR TITLE
feat: Dark Mode Feature Added

### LINKED ISSUE #2: Improve UI
Project Seems really cool, a good UI improvement would help the project reach! 
Hence give me some design ideas and I will try to implement that here

### PR DESCRIPTION
**Pull request by Geen-19**
Dark Mode has been added, check it out.

### CODE REVIEW

**Comment by Zaid-maker** [comment]
Reviewing it Now!

**Review by Zaid-maker — CHANGES_REQUESTED** [review]
image

The Fastest Framework is not showing in dark mode

and also fix the conflict

**Comment by Geen-19** [comment]
I don't have write access in this conflict

**Review by Zaid-maker — APPROVED** [review]
Good to Go!

**Comment by Geen-19** [comment]
@Zaid-maker  how do you have this bot? its soo cool

**Comment by Zaid-maker** [comment]
> @Zaid-maker how do you have this bot? its soo cool

Nothing special tbh! just a regular account managing by myself 👀 but i have plans to use this in CI/CD stuffs in future

**Comment by Geen-19** [comment]
> Thank u so much @Geen-19 ❤️
> 
> By any chance, are u good at making logo? 👀 we need one for this project

Not good with logos :( if you have some other repos to contribute to, I will be happy to commit ❤️

**Comment by Zaid-maker** [comment]
> > By any chance, are u good at making logo? 👀 we need one for this project
> 
> Not good with logos :( if you have some other repos to contribute to, I will be happy to commit ❤️

[check this project](https://github.com/devmirza-bot/package-manager-benchmark) it has same logic as this project ❤️

**Pull request merged**
